# Generated by Django 3.2.5 on 2021-07-29 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20210720_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='due',
            field=models.DateField(default=datetime.date(2021, 7, 29)),
        ),
        migrations.AlterField(
            model_name='work',
            name='due',
            field=models.DateField(default=datetime.date(2021, 7, 29)),
        ),
    ]
